Web-24BM/Models/Ejemplo.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
namespace Web_24BM.Models
{
    public class Ejemplo
    {
        public string Titulo{ get; set; }
        public string Parrafo { get; set; }
    }
}

Web-24BM/Controllers/EjemploController.cs
using Microsoft.AspNetCore.Mvc;
using Web_24BM.Models;

namespace Web_24BM.Controllers
{
    public class EjemploController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Texto = "Esto es un texto desde ejemplo controller";
            TempData["texto2"] = "Texto de sesión";

            Ejemplo model = new Ejemplo();

            model.Titulo = "alejandra cruz";
            model.Parrafo = "Esto es un parrafo";

            return View(model);
        }
        [HttpPost]

        public IActionResult Index(Ejemplo ejemplo)
        {
            if(ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
    }
}

Web-24BM/Views/Ejemplo/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1> @ViewBag.Texto</h1>
<p> @TempData["texto2"]</p>

<h1>@Model.Titulo</h1>
<h1>@Model.Parrafo</h1>

<form asp-action="Index" asp-controller="Ejemplo" method="post">

    <input class="form-control" type="text" name="Titulo" placeholder="Ingresa el titulo" />
    <input class="form-control"  type="text" name="Parrafo" placeholder="Ejemplo" />

    <input type="submit" value="Enviar" class="btn-primary"/>


</form>